# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ce8459e5e62fdde10c6767600c416766b4fb3aa9a4e79a860e7e971d36e8459d02bf2d09a83f07e5a28b1a3fe2d4faf1e1dc2446540dfbf8dad1d601df26bb73

test:
  secret_key_base: 8602688b889b42b9dca9dccd964f1872f62040cd84af4f9f2b4ccab2ee1177971b4a88d11b6612abb07c81d4bc4bd6647e54f96fe74a03012c3ebf71bfaad922

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
